ifdef CONFIG_HTC_DEBUG
obj-y += htc_debug_tools.o
obj-$(CONFIG_HTC_DEBUG_PAGE_USER_TRACE) += debug_page_user_trace.o
obj-$(CONFIG_HTC_PROCESS_DEBUG) += htc_process_debug.o
obj-$(CONFIG_HTC_DEBUG_RESTART_TIMER) += htc_restart_timer_notifier.o
endif
