/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef ECCCI_INTERNAL_OPTION
#define ECCCI_INTERNAL_OPTION
#define FEATURE_GET_MD_GPIO_NUM
#define FEATURE_GET_MD_GPIO_VAL
#define FEATURE_GET_MD_ADC_NUM
#define FEATURE_GET_MD_ADC_VAL
#define FEATURE_GET_MD_EINT_ATTR
#if defined(FEATURE_GET_MD_EINT_ATTR) && !defined(CONFIG_MTK_LEGACY)
#define FEATURE_GET_MD_EINT_ATTR_DTS
#endif

#define FEATURE_GET_MD_BAT_VOL
#define FEATURE_PM_IPO_H
#define FEATURE_SEQ_CHECK_EN
#define FEATURE_POLL_MD_EN

#define FEATURE_SMART_LOGGING
#ifdef CONFIG_HTC_FEATURES_RIL_PCN0007_LWA
#define FEATURE_LWA
#endif 
#define FEATURE_MD1MD3_SHARE_MEM

#if 0 
#define FEATURE_GET_TD_EINT_NUM
#define FEATURE_GET_DRAM_TYPE_CLK
#endif

#define ENABLE_DRAM_API
#define ENABLE_MEM_REMAP_HW
#define ENABLE_CLDMA_AP_SIDE
#define ENABLE_MD_POWER_OFF_CHECK

#ifdef CONFIG_MTK_CONN_MD
#define FEATURE_CONN_MD_EXP_EN
#endif

#ifdef CONFIG_MTK_FPGA
#define FEATURE_FPGA_PORTING
#else
#define FEATURE_RF_CLK_BUF
#define ENABLE_32K_CLK_LESS
#define FEATURE_MD_GET_CLIB_TIME
#define FEATURE_C2K_ALWAYS_ON
#define FEATURE_DBM_SUPPORT

#define ENABLE_EMI_PROTECTION
#ifdef ENABLE_EMI_PROTECTION
#define SET_EMI_STEP_BY_STAGE
 
#endif

#endif
 
#define NO_POWER_OFF_ON_STARTMD
#define NO_START_ON_SUSPEND_RESUME
#define MD_CACHE_TO_NONECACHE
#define MD_UMOLY_EE_SUPPORT
#define TEST_MESSAGE_FOR_BRINGUP

#ifdef FEATURE_SMART_LOGGING
#define SMART_LOGGING_SUPPORT
#endif
#ifdef SMART_LOGGING_SUPPORT


#define CCCI_SMEM_OFFSET_MISC_PART 0
#define CCCI_SMEM_SIZE_MISC_PART (64*1024)
#define CCCI_SMEM_DUMP_SIZE      4096 
#define CCCI_SMEM_SLEEP_MODE_DBG_DUMP 512 
#define CCCI_SMEM_OFFSET_CCCI_DEBUG	CCCI_SMEM_OFFSET_MISC_PART
#define CCCI_SMEM_SIZE_CCCI_DEBUG	2048

#define CCCI_SMEM_OFFSET_SEQERR (CCCI_SMEM_OFFSET_CCCI_DEBUG+0x34)
#define CCCI_SMEM_OFFSET_MDSS_DEBUG	(CCCI_SMEM_OFFSET_CCCI_DEBUG + CCCI_SMEM_SIZE_CCCI_DEBUG)
#define CCCI_SMEM_SIZE_MDSS_DEBUG_UMOLY  8192 
#define CCCI_SMEM_SIZE_MDSS_DEBUG 2048 

#define CCCC_SMEM_CCIF_DUMP_SIZE 16
#define CCCI_SMEM_OFFSET_CCIF_SRAM	(CCCI_SMEM_OFFSET_MDSS_DEBUG+1024-CCCC_SMEM_CCIF_DUMP_SIZE)
#define CCCI_SMEM_OFFSET_EPON		(CCCI_SMEM_OFFSET_MDSS_DEBUG+0x464)
#define CCCI_SMEM_OFFSET_EPON_UMOLY	(CCCI_SMEM_OFFSET_MDSS_DEBUG+0x1030)


#define CCCI_SMEM_SIZE_SLEEP_MODE_DBG 1024
#define CCCI_SMEM_OFFSET_SLEEP_MODE_DBG	(CCCI_SMEM_OFFSET_MISC_PART+CCCI_SMEM_SIZE_MISC_PART \
						-CCCI_SMEM_SIZE_SLEEP_MODE_DBG)
#define CCCI_SMEM_DBM_GUARD_SIZE 8
#define CCCI_SMEM_DBM_SIZE 40
#define CCCI_SMEM_OFFSET_DBM_DEBUG	(CCCI_SMEM_OFFSET_MISC_PART+\
					(CCCI_SMEM_SIZE_MISC_PART-CCCI_SMEM_DBM_SIZE-CCCI_SMEM_DBM_GUARD_SIZE*2))
#define CCCI_SMEM_SIZE_RUNTIME_AP 0x800 
#define CCCI_SMEM_SIZE_RUNTIME_MD 0x800 
#define CCCI_SMEM_SIZE_RUNTIME	(CCCI_SMEM_SIZE_RUNTIME_AP+CCCI_SMEM_SIZE_RUNTIME_MD)
#define CCCI_SMEM_OFFSET_RUNTIME		(CCCI_SMEM_OFFSET_SLEEP_MODE_DBG - CCCI_SMEM_SIZE_RUNTIME)

#define CCCI1_SMEM_OFFSET_SMART_LOGGING (0) 
#define CCCI1_SMEM_SIZE_SMART_LOGGING 0 

#define CCCI3_SMEM_OFFSET_CCIF_SMEM (CCCI_SMEM_OFFSET_MISC_PART+CCCI_SMEM_SIZE_MISC_PART) 
#define CCCI3_SMEM_SIZE_CCIF_SMEM 0 
#define CCCI3_SMEM_END_CCIF_SMEM	(1024*1024)

#define CCCI3_SMEM_OFFSET_SMART_LOGGING (CCCI_SMEM_OFFSET_MISC_PART+CCCI3_SMEM_END_CCIF_SMEM) 
#define CCCI3_SMEM_SIZE_SMART_LOGGING 0 

#ifdef CONFIG_HTC_FEATURES_RIL_PCN0007_LWA
#define CCCI_SMEM_SIZE_LWA_SMEM (3*1024*1024)
#endif 
#else 
#define CCCI_SMEM_DUMP_SIZE      4096 
#define CCCC_SMEM_CCIF_DUMP_SIZE 16 
#define CCCI_SMEM_SLEEP_MODE_DBG_DUMP 512 
#define CCCI_SMEM_DBM_GUARD_SIZE 8
#define CCCI_SMEM_DBM_SIZE 40
#define CCCI_SMEM_SIZE_RUNTIME_AP 0x800 
#define CCCI_SMEM_SIZE_RUNTIME_MD 0x800 
#ifdef CONFIG_HTC_FEATURES_RIL_PCN0007_LWA
#define CCCI_SMEM_SIZE_LWA_SMEM (3*1024*1024) 
#endif 
#define CCCI_SMEM_OFFSET_EXCEPTION 0 
#define CCCI_SMEM_SIZE_EXCEPTION (64*1024) 
#define CCCI_SMEM_OFFSET_CCCI_DEBUG CCCI_SMEM_OFFSET_EXCEPTION 
#define CCCI_SMEM_SIZE_CCCI_DEBUG 2048
#define CCCI_SMEM_OFFSET_MDSS_DEBUG (CCCI_SMEM_OFFSET_EXCEPTION+CCCI_SMEM_SIZE_CCCI_DEBUG) 
#define CCCI_SMEM_OFFSET_CCIF_SRAM (CCCI_SMEM_OFFSET_MDSS_DEBUG+1024-CCCC_SMEM_CCIF_DUMP_SIZE)
#define CCCI_SMEM_OFFSET_EPON (CCCI_SMEM_OFFSET_EXCEPTION+0xC64)
#define CCCI_SMEM_OFFSET_EPON_UMOLY (CCCI_SMEM_OFFSET_EXCEPTION+0x1830)
#define CCCI_SMEM_OFFSET_SEQERR (CCCI_SMEM_OFFSET_EXCEPTION+0x34)
#define CCCI_SMEM_SIZE_MDSS_DEBUG_UMOLY  8192 
#define CCCI_SMEM_SIZE_MDSS_DEBUG 2048 
#define CCCI_SMEM_SIZE_SLEEP_MODE_DBG 1024 
#define CCCI_SMEM_OFFSET_SLEEP_MODE_DBG (CCCI_SMEM_OFFSET_EXCEPTION+CCCI_SMEM_SIZE_EXCEPTION \
										-CCCI_SMEM_SIZE_SLEEP_MODE_DBG)
#define CCCI_SMEM_OFFSET_DBM_DEBUG (CCCI_SMEM_OFFSET_EXCEPTION+(64*1024-CCCI_SMEM_DBM_SIZE-CCCI_SMEM_DBM_GUARD_SIZE*2))
#define CCCI_SMEM_OFFSET_RUNTIME (CCCI_SMEM_OFFSET_EXCEPTION+CCCI_SMEM_SIZE_EXCEPTION)
#define CCCI_SMEM_SIZE_RUNTIME	(CCCI_SMEM_SIZE_RUNTIME_AP+CCCI_SMEM_SIZE_RUNTIME_MD)

#define CCCI_SMEM_OFFSET_SMART_LOGGING (CCCI_SMEM_OFFSET_RUNTIME+CCCI_SMEM_SIZE_RUNTIME) 
#define CCCI_SMEM_SIZE_SMART_LOGGING 0 

#define CCCI_SMEM_OFFSET_CCIF_SMEM (CCCI_SMEM_OFFSET_RUNTIME+CCCI_SMEM_SIZE_RUNTIME) 
#define CCCI_SMEM_SIZE_CCIF_SMEM 0 
#endif 

#define AP_PLATFORM_INFO    "MT6755E1"
#define CCCI_MTU            (3584-128)
#define CCCI_NET_MTU        (1500)
#define SKB_POOL_SIZE_4K    (256)	
#define SKB_POOL_SIZE_1_5K  (256)	
#define SKB_POOL_SIZE_16    (64)	
#define BM_POOL_SIZE        (SKB_POOL_SIZE_4K+SKB_POOL_SIZE_1_5K+SKB_POOL_SIZE_16)
#define RELOAD_TH            3	
#define MD_HEADER_VER_NO    (3)
#define MEM_LAY_OUT_VER     (1)
#define AP_MD_HS_V2          2	

#define CCCI_MEM_ALIGN      (SZ_32M)
#define CCCI_SMEM_ALIGN_MD1 (0x200000)	
#define CCCI_SMEM_ALIGN_MD2 (0x200000)	

#define CURR_SEC_CCCI_SYNC_VER (1)	
#define CCCI_DRIVER_VER     0x20110118

#define IPC_L4C_MSG_ID_LEN   (0x40)

#define CCCI_LOG_LEVEL  (5)

#ifdef CONFIG_HTC_FEATURES_RIL_PCN0004_HTC_GARBAGE_FILTER
#define FEATURE_GARBAGE_FILTER_SUPPORT
#endif

#ifdef CONFIG_HTC_FEATURES_RIL_PCN0005_C2K_POWER_DEBUG
#define TRAFFIC_MONITOR_INTERVAL_C2K 20	
#endif

#endif
